### ISSUE TITLE
Error: Data Model definition not found:/Custom/Human Capital Management/FusionSQLtoolTest1/FusionSQLToolDM.xdm

### ISSUE THREAD

**Issue by johnboychan** [anandvegaraju/FusionSQLite#2]
Hi Anand,

[1] I am getting the attached error message when I try to run a simple query.
oracle.xdo.webservice.exception.OperationFailedException: PublicReportService::generateReport for reportAbsolutePath [/Custom/Human Capital Management/FusionSQLtoolTest1/FSTreport.xdo] failed: due to oracle.xdo.server.ReportException: oracle.xdo.servlet.CreateException: oracle.xdo.servlet.CreateException: oracle.xdo.servlet.CreateException: Data Model definition not found:/Custom/Human Capital Management/FusionSQLtoolTest1/FusionSQLToolDM.xdm

John > The above error seems to indicate that I need a BI data model in the Custom folder?

[2] I downloaded the exe and followed the install process.

[3] I entered our dev pod and the user I am connecting with has the 'Human Capital Management Integration  Specialist' role.

![image](https://user-images.githubusercontent.com/11960330/92602557-2f489400-f2a6-11ea-979e-ee3edc6b1f20.png)

Am I missing something obvious?

Cheers
John

**Comment by anandvegaraju** [comment]
Hi John,

Thanks for reaching out. Hope you are doing well. Did you click on
"Initialize Environment" before running your query? Download the
latest/updated exe (same link), click on the "Initialize Environment"
button after entering your instance URL, username and password. This should
create a data model and report in the path -> Custom/Human Capital
Management/FusionSQLtoolTest1. Please let me know if you continue to face
this problem.

Thanks and Regards,
Anand

**Comment by johnboychan** [comment]
Hi Anand,

I have tried again and getting closer.

[1] I have downloaded the latest and updated exe and clicked on "Initialize Environment. I can see the data model and report in path: Custom/Human Capital Management/FusionSQLtoolTest1

[2] I get the following error when running the following query.

select * from per_all_assignments_m
where person_id = 100000005343733
and rownum < 10;

or

select * from per_all_assignments_m
where rownum < 10;



oracle.xdo.webservice.exception.OperationFailedException: PublicReportService::generateReport for reportAbsolutePath [/Custom/Human Capital Management/FusionSQLtoolTest1/FSTreport.xdo] failed: due to oracle.xdo.server.ServerException: oracle.xdo.servlet.data.DataException: oracle.xdo.servlet.data.DataException: oracle.xdo.servlet.data.DataException: oracle.xdo.servlet.data.DataException: oracle.xdo.XDOException: SQLInjection Error: Invalid parameter value select * from per_all_assignments_m
where rownum < 10;

I have attached screenshots.

Do you know why I would get SQLInjection Error?

Kind Regards
John
[FusionSQLite 20200921.docx](https://github.com/anandvegaraju/FusionSQLite/files/5255233/FusionSQLite.20200921.docx)

**Comment by anandvegaraju** [comment]
Hi John,

Can you try again after removing the semicolon?

Thanks and Regards,
Anand

**Comment by johnboychan** [comment]
Hi Anand,

I have tried initializing again and running without semi colon but still get the same error.

This is the cloud version of OBIEE we are using.
Oracle Business Intelligence 11.1.1.9

This is the release we are on.
Oracle Cloud Application
20C (11.13.20.07.0)


Cheers
John
[FusionSQLite 20200921_2.docx](https://github.com/anandvegaraju/FusionSQLite/files/5255354/FusionSQLite.20200921_2.docx)

**Comment by anandvegaraju** [comment]
That's strange. I'm able to run it. Can you try passing the select query as
a parameter to the data model directly?

[image: image.png]

**Comment by johnboychan** [comment]
Hi Anand,

I tried running with the default query 'select * from dual' in the datamodel and got the same error. I tried with my original query and got the same error. I tried removing the * character e.g

select assignment_number from per_all_assignments_f where rownum < 3 and still get the error.

I think our OBIEE instance may have some setting to stop anything that looks like sql statements from running? incase it looks like sql injection??? I am checking BI documentation.

[FusionSQLToolDM_-2.xml.txt](https://github.com/anandvegaraju/FusionSQLite/files/5255536/FusionSQLToolDM_-2.xml.txt)
[FusionSQLite 20200921_3.docx](https://github.com/anandvegaraju/FusionSQLite/files/5255542/FusionSQLite.20200921_3.docx)

Cheers
John

**Comment by anandvegaraju** [comment]
Yeah. You're probably right. You can check your BI administrator settings
for such protection settings.

**Comment by anandvegaraju** [comment]
Will work on a new approach to avoid ref cursor soon. Maybe that would
workaround the problem in your case.

**Comment by johnboychan** [comment]
Hi Anand,

I cant find such a setting and was about to raise SR with Oracle as I cannot find the SQLInjection error mentioned in Oracle Cloud Support. If I hard code the sql then it works fine and I can see the details in the FusionSQL UI.


DECLARE
    type refcursor is REF CURSOR;
    xdo_cursor refcursor;
        queryStr varchar2(32767);
    BEGIN
    queryStr := 'select assignment_number from per_all_assignments_m where rownum < 3';
    OPEN :xdo_cursor FOR queryStr;
END;

I am not in a hurry so happy to wait on your new approach

CHeers
John

**Comment by johnboychan** [comment]
Hi Anand,

I will close this issue after it had been highlighted to me the following link
https://www.oracle.com/webfolder/technetwork/tutorials/tutorial/cloud/r13/wn/common/releases/20C/20C-common-wn.htm#T21584

Look forward to your new solution.

Cheers
John

**Comment by anandvegaraju** [comment]
Hi John,

Can you please try [this ](https://www.dropbox.com/s/e9tbsp8nj26st8s/FusionSQLitev1-1.exe?dl=0) version and let me know if it works? 

Regards,
Anand

**Comment by masebu** [comment]
Works for me on HCM 20D 😀
nice !

**Comment by anandvegaraju** [comment]
Great! I Will work on optimizing this further.
